// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(robot) {
    var clearTimer, startTimer, timer;
    timer = null;
    startTimer = function(user, room) {
      return timer = setTimeout(function() {
        robot.send({
          room: room
        }, user + ": 進捗どうですか？");
        startTimer(user, room);
      }, 30 * 60 * 1000);
    };
    clearTimer = function() {
      if (timer !== null) {
        clearTimeout(timer);
        timer = null;
        return true;
      }
      return false;
    };
    robot.respond(/進捗 start/i, function(msg) {
      var room, user;
      clearTimer();
      user = msg.message.user.name;
      room = msg.message.user.room;
      startTimer(user, room);
      return msg.send("進捗 start");
    });
    return robot.respond(/進捗 stop/i, function(msg) {
      if (clearTimer()) {
        return msg.send("進捗 stop");
      }
    });
  };

}).call(this);

//# sourceMappingURL=example.js.map
